### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by rising-stark**
Added the PULL_REQUEST_TEMPLATE.md in a separate branch Patch-1.
You can review it now.

### CODE REVIEW

**Comment by arshadkazmi42** [comment]
You can create new PR without closing also.
You should use someother branch name

**Comment by arshadkazmi42** [comment]
This has both the changes. 
We have already merged a PR for PULL_REQUEST_TEMPLATE here #20 
You can remove your PULL_REQUEST_TEMPLATE changes and just add the readme changes

**Comment by rising-stark** [comment]
Okay done. I have resolved the conflict

**Comment by arshadkazmi42** [comment]
@rising-stark 
You did multiple fixes in the same branch. 
Next time onwards try following these steps

    - Fork this repo
    - Clone the forked repo
    - Create a new branch using `git checkout -b issue_name_or_number` (here issue_number_or_number should be different branch names for different issues you  are fixing)
    - Make required changes for the particular issue
    - Commit and push your changes.
    - Open the repo in the browser, you will get an option to create PR.
    - Create PR and you are done.

**Comment by rising-stark** [comment]
Okay will take care of that next time onwards. And sorry for the inconvenience caused due to my unintelligible acts. But I surely will perform better as I get to actually what is all about "Contribution".

**Comment by arshadkazmi42** [comment]
You can follow these twitter accounts
https://twitter.com/first_tmrs_only
https://twitter.com/first_issues

These accounts tweets easy issues from github which will be good for open source beginners

**Pull request merged**
