### PR TITLE
Add PR template

### LINKED ISSUE #7: Add PR Template
Add a `PULL_REQUEST_TEMPLATE.md` with following details

```
Fixes #issuenumber

Check everything which applies
[] I have added the issue number for which this pull request is created.
```

### PR DESCRIPTION
**Pull request by SubhamPaul21**
Added contents as mentioned

Fixes #7

### CODE REVIEW

**Comment by arshadkazmi42** [comment]
Congrats on landing your first patch

**Comment by SubhamPaul21** [comment]
wow.... thank you so much.... Feels great :D

**Comment by arshadkazmi42** [comment]
You can follow this bot on twitter, which tweets all `good-first-issues`. It will be easy to find new issues to work on https://twitter.com/first_issues

**Comment by SubhamPaul21** [comment]
Yah Sure will be doing this more now.... thank you for the first helping hand...

**Pull request merged**
