### PR TITLE
Fix a little import error in test.py

### PR DESCRIPTION
**Pull request by zswen**
When I run test.py. I received: ImportError: No module named first_timers. May I fix this issue? Should I open an issue first and create a pull request? Please let me know if I did wrong.

### CODE REVIEW

**Comment by arshadkazmi42** [comment]
This is a good observation, thanks for finding this out.
I will get this reviewed ASAP

**Comment by arshadkazmi42** [comment]
This is the error

screenshot from 2019-01-15 09-22-34

**Comment by zswen** [comment]
Working on it!

**Comment by zswen** [comment]
It's all about relative path/absolute path. Still working on it.

**Comment by zswen** [comment]
So currently if you run test.py under /test directory, it will run without any issue. If you go one level above and run `python tests/test.py` it will fail. Still working on a solution.

**Comment by zswen** [comment]
@arshadkazmi42 Fixed. We can run tests.py from anywhere.

**Comment by arshadkazmi42** [comment]
It was still failing for the path. Made few changes.

**Pull request merged**
